### ISSUE TITLE
Polygon/grid intersection

### ISSUE THREAD

**Issue by tomalrussell** [nismod/snail#20]
Add an intersections method to handle polygon intersections with the grid.

A Polygon is defined by one or more LinearRings:
- a LinearRing is a LineString or Vector<Coord> where the first and last coordinate are the same
- the first LinearRing of a Polygon defines its outer boundary
- subsequent LinearRings define holes. Initial implementation can ignore holes if that makes it much easier.

Splitting a polygon along grid lines might result in:
- the original polygon, if it lies entirely within a single grid cell
- some irregular polygons, with straight edges/corners where they meet the grid lines
- some rectangular polygons, matching the bounds of grid cells, where the polygon contains one or more whole cells

Implementation idea, follow the [scanline rendering](https://en.wikipedia.org/wiki/Scanline_rendering) algorithm, but output polygons rather than filling in raster values:
- split LinearRing into list of edges `Vector<Line2>`
- split all these edges on the grid (`Grid::findIntersections(Line2)`)
- sort edges by min y-coordinate
- keep a reference to the "current" row (scanline) of cells, defined by min y-coordinate
- maintain list of active edges
- start with the first edge, add it to active edges, set the "current" row to be `floor(min-y)` to get the bottom of the cell
- add edges to active as long as they have min-y less than the next row's y-coordinate
  - when an edge becomes active, it either 
    - starts a new polygon piece (if neither endpoint is shared with an active edge within the same cell)
    - joins a polygon piece
  - add cell edges to polygon pieces where endpoints intersect the grid
  - to close out a row, add horizontal edges; these should be copied to initialise active edges for the next loop around
- repeat for each row until all edges are dealt with

Comments:
- splitting all the edges on the grid up front seems to simplify things, as all the edges are strictly within grid cells for the rest of the routine
- for the polygon construction bit at the core of the routine: do we need to retain the original order of Line2s to piece back together a more complicated polygon piece? 
- We may need to include parts of grid cell lines to complete the pieces. It seems like this could be handled by "top of the cell" and "bottom of the cell" sections for special cases, including making sure we include all "entirely-interior" cells that don't intersect with the polygon boundary but are contained.
- Might be better to split LinearRing > Vector<LineString> rather than dealing with Line2, where the LineString endpoints by construction intersect cell boundaries
- Could think about shooting rays along the grid lines (horizontal and vertical): we start outside the polygon; when we hit the first polygon boundary edge (or any odd edge) we are inside, when we hit the next (even) edge we are outside again...

**Comment by tomalrussell** [comment]
As discussed - with the ray-shooting idea, we could assemble all the pieces of edges by considering a ray going through the polygon along each grid line, then connect them together into small polygons (one or more per cell) to output.

Might be useful to ensure that the polygon boundary is counter-clockwise (and that holes go clockwise, if we allow them) - then connecting edge-pieces into polygons should be unambiguous, following the same counter-clockwise order.

**Comment by tlestang** [comment]
Prototype Python script for ray-shooting approach is proposed in #25 

Draft C++ implementation is proposed in #26

**Comment by tomalrussell** [comment]
Closed by #25 and #26
