### ISSUE TITLE
CMake error when installing

### ISSUE THREAD

**Issue by dianajjaramillo** [nismod/snail#44]
When I try installing snail on my mac I am receiving CMake errors both using "pip install ." and "python setup.py develop". I also tried installing snail on a Linux cluster, and I also receive CMake errors. I have attached the errors I receive on both as well as the CMake error log.
[linux_error.pdf](https://github.com/nismod/snail/files/7498651/linux_error.pdf)
[mac_error.pdf](https://github.com/nismod/snail/files/7498652/mac_error.pdf)
[mac_error_log.pdf](https://github.com/nismod/snail/files/7498653/mac_error_log.pdf)
[mac_error_pip.pdf](https://github.com/nismod/snail/files/7498682/mac_error_pip.pdf)

**Comment by tomalrussell** [comment]
Thanks for the error report. Could you try pulling in the latest changes and running `pip install .` again? I've had a go at reworking the build configuration and dependencies.

See updated notes on different installation methods in [README#installation](https://github.com/nismod/snail/tree/dd1924b1a50b983adfe38682d356a51b9a3ffe7a#installation).

**Comment by tomalrussell** [comment]
Hi @dianajjaramillo is this all fixed for you now?

Either route should work:
- `pip install -e .` from a checkout of this repository
- `pip install nismod-snail` with no need to clone this repository, downloaded by pip from https://pypi.org/project/nismod-snail/
